-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTJA7gKRP4MZgK2qU
ypWVWQjrygst6x57sgBx0gFa5eWgCgYIKoZIzj0DAQehRANCAASkYq9e5oVyO2Es
mTwCKYPcR6mtZZcLweOQiDkRbvwxbr23N60JtwDBQKPkkRpYHE4gysn3aBZs9APf
qhD5Ontq
-----END PRIVATE KEY-----